apiVersion: v1
kind: Service
metadata:
  name: home-controls-service
  namespace: home-controls
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: home-controls-service